version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd react
      - npm ci

  build:
    commands:
      - echo Building React app...
      - npm run build
      - echo Build complete.

artifacts:
  base-directory: react/build
  files:
    - '**/*'

cache:
  paths:
    - react/node_modules/**/*
